[2024-09-24T17:58:21.856+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-24T17:58:21.870+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: random_forest_classifier_dag.prepare_data manual__2024-09-24T17:58:15.950537+00:00 [queued]>
[2024-09-24T17:58:21.878+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: random_forest_classifier_dag.prepare_data manual__2024-09-24T17:58:15.950537+00:00 [queued]>
[2024-09-24T17:58:21.880+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-24T17:58:21.890+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): prepare_data> on 2024-09-24 17:58:15.950537+00:00
[2024-09-24T17:58:21.898+0000] {standard_task_runner.py:64} INFO - Started process 33952 to run task
[2024-09-24T17:58:21.901+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'random_forest_classifier_dag', 'prepare_data', 'manual__2024-09-24T17:58:15.950537+00:00', '--job-id', '414', '--raw', '--subdir', 'DAGS_FOLDER/***/dags/.ipynb_checkpoints/hw1-checkpoint.py', '--cfg-path', '/tmp/tmpdj_pnd50']
[2024-09-24T17:58:21.907+0000] {standard_task_runner.py:91} INFO - Job 414: Subtask prepare_data
[2024-09-24T17:58:22.000+0000] {task_command.py:426} INFO - Running <TaskInstance: random_forest_classifier_dag.prepare_data manual__2024-09-24T17:58:15.950537+00:00 [running]> on host 82997fc6deb7
[2024-09-24T17:58:22.098+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='alexvlg34@gmail.com' AIRFLOW_CTX_DAG_OWNER='Alex Trigolos' AIRFLOW_CTX_DAG_ID='random_forest_classifier_dag' AIRFLOW_CTX_TASK_ID='prepare_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-24T17:58:15.950537+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-24T17:58:15.950537+00:00'
[2024-09-24T17:58:22.099+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-24T17:58:22.108+0000] {hw1-checkpoint.py:115} INFO - Prepare data...
[2024-09-24T17:58:22.109+0000] {s3.py:1422} INFO - Downloading source S3 file from Bucket testmlops with path AlexTrigolos/RandomForestClassifier/datasets/dataset.pkl
[2024-09-24T17:58:22.116+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-09-24T17:58:22.117+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-09-24T17:58:22.468+0000] {hw1-checkpoint.py:79} INFO - /tmp/***_tmp_g29d5305
[2024-09-24T17:58:22.519+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-09-24T17:58:22.520+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-09-24T17:58:22.818+0000] {hw1-checkpoint.py:147} INFO - Prepared data.
[2024-09-24T17:58:22.819+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-24T17:58:22.820+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-24T17:58:22.828+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=random_forest_classifier_dag, task_id=prepare_data, run_id=manual__2024-09-24T17:58:15.950537+00:00, execution_date=20240924T175815, start_date=20240924T175821, end_date=20240924T175822
[2024-09-24T17:58:22.879+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-09-24T17:58:22.899+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-24T17:58:22.903+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
