[2024-10-04T12:24:35.639+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-04T12:24:35.664+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Alex_Trigolos.task_init manual__2024-10-04T12:24:32.261499+00:00 [queued]>
[2024-10-04T12:24:35.700+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Alex_Trigolos.task_init manual__2024-10-04T12:24:32.261499+00:00 [queued]>
[2024-10-04T12:24:35.702+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-04T12:24:35.728+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): task_init> on 2024-10-04 12:24:32.261499+00:00
[2024-10-04T12:24:35.741+0000] {standard_task_runner.py:64} INFO - Started process 70043 to run task
[2024-10-04T12:24:35.746+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Alex_Trigolos', 'task_init', 'manual__2024-10-04T12:24:32.261499+00:00', '--job-id', '848', '--raw', '--subdir', 'DAGS_FOLDER/***/dags/project.py', '--cfg-path', '/tmp/tmpqq5364v7']
[2024-10-04T12:24:35.749+0000] {standard_task_runner.py:91} INFO - Job 848: Subtask task_init
[2024-10-04T12:24:35.823+0000] {task_command.py:426} INFO - Running <TaskInstance: Alex_Trigolos.task_init manual__2024-10-04T12:24:32.261499+00:00 [running]> on host 4b5f1410d111
[2024-10-04T12:24:35.949+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='alexvlg34@gmail.com' AIRFLOW_CTX_DAG_OWNER='Alex Trigolos' AIRFLOW_CTX_DAG_ID='Alex_Trigolos' AIRFLOW_CTX_TASK_ID='task_init' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T12:24:32.261499+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-04T12:24:32.261499+00:00'
[2024-10-04T12:24:35.951+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-04T12:24:35.970+0000] {project.py:99} INFO - Train pipeline started.
[2024-10-04T12:24:36.277+0000] {logging_mixin.py:188} WARNING - 2024/10/04 12:24:36 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2024-10-04T12:24:36.348+0000] {logging_mixin.py:188} WARNING - 2024/10/04 12:24:36 INFO mlflow.tracking._tracking_service.client: üèÉ View run ursatap at: http://mlflow-service:5000/#/experiments/873725604529716173/runs/214e689418f74103b443741b6384d669.
[2024-10-04T12:24:36.349+0000] {logging_mixin.py:188} WARNING - 2024/10/04 12:24:36 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow-service:5000/#/experiments/873725604529716173.
[2024-10-04T12:24:36.500+0000] {logging_mixin.py:188} WARNING - 2024/10/04 12:24:36 INFO mlflow.tracking._tracking_service.client: üèÉ View run abc at: http://mlflow-service:5000/#/experiments/873725604529716173/runs/96f60ad7dda640d39ea04f57608106c4.
[2024-10-04T12:24:36.501+0000] {logging_mixin.py:188} WARNING - 2024/10/04 12:24:36 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow-service:5000/#/experiments/873725604529716173.
[2024-10-04T12:24:36.580+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-04T12:24:36.581+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-04T12:24:36.596+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Alex_Trigolos, task_id=task_init, run_id=manual__2024-10-04T12:24:32.261499+00:00, execution_date=20241004T122432, start_date=20241004T122435, end_date=20241004T122436
[2024-10-04T12:24:36.662+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-10-04T12:24:36.704+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-04T12:24:36.709+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
