[2024-09-24T18:47:06.855+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-24T18:47:06.868+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: random_forest_classifier_dag.rfc_get_data manual__2024-09-24T18:47:03.919011+00:00 [queued]>
[2024-09-24T18:47:06.875+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: random_forest_classifier_dag.rfc_get_data manual__2024-09-24T18:47:03.919011+00:00 [queued]>
[2024-09-24T18:47:06.876+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-24T18:47:06.885+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): rfc_get_data> on 2024-09-24 18:47:03.919011+00:00
[2024-09-24T18:47:06.892+0000] {standard_task_runner.py:64} INFO - Started process 46605 to run task
[2024-09-24T18:47:06.894+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'random_forest_classifier_dag', 'rfc_get_data', 'manual__2024-09-24T18:47:03.919011+00:00', '--job-id', '458', '--raw', '--subdir', 'DAGS_FOLDER/***/dags/.ipynb_checkpoints/hw1-checkpoint.py', '--cfg-path', '/tmp/tmpi8c39ch8']
[2024-09-24T18:47:06.896+0000] {standard_task_runner.py:91} INFO - Job 458: Subtask rfc_get_data
[2024-09-24T18:47:06.930+0000] {task_command.py:426} INFO - Running <TaskInstance: random_forest_classifier_dag.rfc_get_data manual__2024-09-24T18:47:03.919011+00:00 [running]> on host 82997fc6deb7
[2024-09-24T18:47:07.000+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='alexvlg34@gmail.com' AIRFLOW_CTX_DAG_OWNER='Alex Trigolos' AIRFLOW_CTX_DAG_ID='random_forest_classifier_dag' AIRFLOW_CTX_TASK_ID='rfc_get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-24T18:47:03.919011+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-24T18:47:03.919011+00:00'
[2024-09-24T18:47:07.001+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-24T18:47:07.009+0000] {hw1-checkpoint.py:66} INFO - Get data...
[2024-09-24T18:47:07.392+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-09-24T18:47:07.393+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-09-24T18:47:08.016+0000] {hw1-checkpoint.py:84} INFO - Finish get data.
[2024-09-24T18:47:08.016+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-24T18:47:08.017+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-24T18:47:08.025+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=random_forest_classifier_dag, task_id=rfc_get_data, run_id=manual__2024-09-24T18:47:03.919011+00:00, execution_date=20240924T184703, start_date=20240924T184706, end_date=20240924T184708
[2024-09-24T18:47:08.072+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-09-24T18:47:08.080+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
