[2024-09-24T18:57:07.436+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-24T18:57:07.449+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: random_forest_classifier_dag.rfc_get_data manual__2024-09-24T18:57:03.907079+00:00 [queued]>
[2024-09-24T18:57:07.455+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: random_forest_classifier_dag.rfc_get_data manual__2024-09-24T18:57:03.907079+00:00 [queued]>
[2024-09-24T18:57:07.456+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-24T18:57:07.466+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): rfc_get_data> on 2024-09-24 18:57:03.907079+00:00
[2024-09-24T18:57:07.473+0000] {standard_task_runner.py:64} INFO - Started process 50194 to run task
[2024-09-24T18:57:07.476+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'random_forest_classifier_dag', 'rfc_get_data', 'manual__2024-09-24T18:57:03.907079+00:00', '--job-id', '500', '--raw', '--subdir', 'DAGS_FOLDER/***/dags/.ipynb_checkpoints/hw1-checkpoint.py', '--cfg-path', '/tmp/tmp84z3gt_8']
[2024-09-24T18:57:07.478+0000] {standard_task_runner.py:91} INFO - Job 500: Subtask rfc_get_data
[2024-09-24T18:57:07.515+0000] {task_command.py:426} INFO - Running <TaskInstance: random_forest_classifier_dag.rfc_get_data manual__2024-09-24T18:57:03.907079+00:00 [running]> on host 82997fc6deb7
[2024-09-24T18:57:07.580+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='alexvlg34@gmail.com' AIRFLOW_CTX_DAG_OWNER='Alex Trigolos' AIRFLOW_CTX_DAG_ID='random_forest_classifier_dag' AIRFLOW_CTX_TASK_ID='rfc_get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-24T18:57:03.907079+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-24T18:57:03.907079+00:00'
[2024-09-24T18:57:07.582+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-24T18:57:07.592+0000] {hw1-checkpoint.py:99} INFO - Get data...
[2024-09-24T18:57:07.788+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-09-24T18:57:07.789+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-09-24T18:57:08.332+0000] {hw1-checkpoint.py:111} INFO - Finish get data.
[2024-09-24T18:57:08.332+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-24T18:57:08.333+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-24T18:57:08.342+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=random_forest_classifier_dag, task_id=rfc_get_data, run_id=manual__2024-09-24T18:57:03.907079+00:00, execution_date=20240924T185703, start_date=20240924T185707, end_date=20240924T185708
[2024-09-24T18:57:08.373+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-09-24T18:57:08.382+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
