[2024-09-24T18:46:58.166+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-24T18:46:58.179+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: decision_tree_classifier_dag.dtc_get_data manual__2024-09-24T18:46:54.456252+00:00 [queued]>
[2024-09-24T18:46:58.185+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: decision_tree_classifier_dag.dtc_get_data manual__2024-09-24T18:46:54.456252+00:00 [queued]>
[2024-09-24T18:46:58.187+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-24T18:46:58.197+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): dtc_get_data> on 2024-09-24 18:46:54.456252+00:00
[2024-09-24T18:46:58.205+0000] {standard_task_runner.py:64} INFO - Started process 46407 to run task
[2024-09-24T18:46:58.207+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'decision_tree_classifier_dag', 'dtc_get_data', 'manual__2024-09-24T18:46:54.456252+00:00', '--job-id', '451', '--raw', '--subdir', 'DAGS_FOLDER/***/dags/.ipynb_checkpoints/hw1-checkpoint.py', '--cfg-path', '/tmp/tmpqxm5n6a6']
[2024-09-24T18:46:58.209+0000] {standard_task_runner.py:91} INFO - Job 451: Subtask dtc_get_data
[2024-09-24T18:46:58.247+0000] {task_command.py:426} INFO - Running <TaskInstance: decision_tree_classifier_dag.dtc_get_data manual__2024-09-24T18:46:54.456252+00:00 [running]> on host 82997fc6deb7
[2024-09-24T18:46:58.313+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='alexvlg34@gmail.com' AIRFLOW_CTX_DAG_OWNER='Alex Trigolos' AIRFLOW_CTX_DAG_ID='decision_tree_classifier_dag' AIRFLOW_CTX_TASK_ID='dtc_get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-24T18:46:54.456252+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-24T18:46:54.456252+00:00'
[2024-09-24T18:46:58.314+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-24T18:46:58.323+0000] {hw1-checkpoint.py:66} INFO - Get data...
[2024-09-24T18:46:58.558+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-09-24T18:46:58.560+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-09-24T18:46:59.119+0000] {hw1-checkpoint.py:84} INFO - Finish get data.
[2024-09-24T18:46:59.120+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-24T18:46:59.121+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-24T18:46:59.130+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=decision_tree_classifier_dag, task_id=dtc_get_data, run_id=manual__2024-09-24T18:46:54.456252+00:00, execution_date=20240924T184654, start_date=20240924T184658, end_date=20240924T184659
[2024-09-24T18:46:59.184+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-09-24T18:46:59.206+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-24T18:46:59.209+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
